export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';

export const HEADLINES_LIST_REQUEST = 'HEADLINES_LIST_REQUEST';
export const HEADLINES_LIST_SUCCESS = 'HEADLINES_LIST_SUCCESS';
export const HEADLINES_LIST_FAIL = 'HEADLINES_LIST_FAIL';
