export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_INACTIVE_DETAILS_REQUEST = 'USER_INACTIVE_DETAILS_REQUEST';
export const USER_INACTIVE_DETAILS_SUCCESS = 'USER_INACTIVE_DETAILS_SUCCESS';
export const USER_INACTIVE_DETAILS_FAIL = 'USER_INACTIVE_DETAILS_FAIL';

export const USER_CONFIRM_ACCOUNT_REQUEST = 'USER_CONFIRM_ACCOUNT_REQUEST';
export const USER_CONFIRM_ACCOUNT_SUCCESS = 'USER_CONFIRM_ACCOUNT_SUCCESS';
export const USER_CONFIRM_ACCOUNT_FAIL = 'USER_CONFIRM_ACCOUNT_FAIL';

export const USER_USERNAME_EXIST_CHECK = 'USER_USERNAME_EXIST_CHECK';
export const USER_EMAIL_EXIST_CHECK = 'USER_EMAIL_EXIST_CHECK';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_PROFILE_DETAILS_REQUEST = 'USER_PROFILE_DETAILS_REQUEST';
export const USER_PROFILE_DETAILS_SUCCESS = 'USER_PROFILE_DETAILS_SUCCESS';
export const USER_PROFILE_DETAILS_FAIL = 'USER_PROFILE_DETAILS_FAIL';

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';

export const USER_PROFILE_DELETE_REQUEST = 'USER_PROFILE_DELETE_REQUEST';
export const USER_PROFILE_DELETE_SUCCESS = 'USER_PROFILE_DELETE_SUCCESS';
export const USER_PROFILE_DELETE_FAIL = 'USER_PROFILE_DELETE_FAIL';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';